spring:
  datasource:
    initialization-mode: never
  main:
    log-startup-info: true
  logging:
    level:
      org.springframework.boot.autoconfigure: DEBUG
      com.user_aggregator.config: DEBUG

aggregator:
  data-sources:
    - name: database_postgres
      strategy: postgres
      url: jdbc:postgresql://localhost:5432/database_postgres
      user: postgres
      password: root
      table: users
      mapping:
        id: user_id
        username: login
        name: first_name
        surname: last_name

    - name: database_mysql
      strategy: mysql
      url: jdbc:mysql://localhost:3306/database_mysql
      user: root
      password: root
      table: user_table
      mapping:
        id: ldap_login
        username: ldap_login
        name: name
        surname: surname
